`use client`

import Header from "./Component/Header"
import Footer from "./Component/Footer";
import Button from "./Component/Buttom";

import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>

        <Header />
        {children}
        <Footer />
        <Button />
        

      </body>
    </html>
  );
}
